runtime: nodejs20
 
instance_class: F2
 
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
 
env_variables:
  NODE_ENV: "production"
 
entrypoint: npm build
 
handlers:
- url: /static
  static_dir: build/static
 
- url: /(.*\.(json|ico|jpg|png|js))$
  static_files: build/\1
  upload: build/.*\.(json|ico|jpg|png|js)$
 
- url: .*
  static_files: build/index.html
  upload: build/index.html
